### ISSUE TITLE
declare mocha a dev dependency

### ISSUE THREAD

**Issue by lucianolxp** [starkbank/ecdsa-node#6]
currently `mocha` is declared as a production dependency. This makes our production code include an additional 15.4 Mb of unnecessary packages

**Comment by cdottori-stark** [comment]
Refactor published on release 1.1.1, thanks for the input!

**Comment by lucianolxp** [comment]
Do you plan to release it to npm? It is still on 0.0.3 there (and also the dependency of @sendgrid/eventwebhook)

**Comment by cdottori-stark** [comment]
It was released yesterday at starkbank-ecdsa (v1.1.1), you are probably looking at our deprecated package, @starkbank/ecdsa (v0.0.3)!

**Comment by lucianolxp** [comment]
ah ok, i will open an issue on @sendgrid/eventwebhook, thanks
